# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Java Exercise Mobile Features - Maven Build

on:
  release:
    types: [created]
  push:
    branches:
      - main
      - git-worflows
  pull_request:
    branches:
      - main


jobs:
  build:
    uses: https://github.com/dede999/MobileJavaExercise/.github/workflows/maven-setup.yml
    runs-on: ubuntu-latest
    steps:
      - name: Build with Maven
        run: mvn clean install

  test:
    uses: https://github.com/dede999/MobileJavaExercise/.github/workflows/maven-setup.yml
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: mvn test

    # - name: Publish to GitHub Packages Apache Maven
    #   run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
    #   env:
    #     GITHUB_TOKEN: ${{ github.token }}
